// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserAccessRequest.Data;

#nullable disable

namespace UserAccessRequest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412010746___FieldAddSection")]
    partial class __FieldAddSection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserAccessRequest.Model.Database.Fields", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FieldIsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("FieldPlaceholder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FiledName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.Form", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormDepartment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.FormFields", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("FormId");

                    b.ToTable("formFields");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.RequestForms", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldsId")
                        .HasColumnType("text");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<string>("RequestStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldsId");

                    b.HasIndex("FormId");

                    b.ToTable("RequestForms");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.RequestFormsResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text");

                    b.Property<string>("RequestFormId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("RequestFormId");

                    b.ToTable("RequestFormsResult");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.FormFields", b =>
                {
                    b.HasOne("UserAccessRequest.Model.Database.Fields", "Field")
                        .WithMany("FieldForms")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserAccessRequest.Model.Database.Form", "Form")
                        .WithMany("FormFields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.RequestForms", b =>
                {
                    b.HasOne("UserAccessRequest.Model.Database.Fields", null)
                        .WithMany("RequestForms")
                        .HasForeignKey("FieldsId");

                    b.HasOne("UserAccessRequest.Model.Database.Form", "Form")
                        .WithMany("RequestForms")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.RequestFormsResult", b =>
                {
                    b.HasOne("UserAccessRequest.Model.Database.Fields", "Fields")
                        .WithMany("ResultFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserAccessRequest.Model.Database.RequestForms", "RequestForms")
                        .WithMany("RequestFormsResult")
                        .HasForeignKey("RequestFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fields");

                    b.Navigation("RequestForms");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.Fields", b =>
                {
                    b.Navigation("FieldForms");

                    b.Navigation("RequestForms");

                    b.Navigation("ResultFields");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.Form", b =>
                {
                    b.Navigation("FormFields");

                    b.Navigation("RequestForms");
                });

            modelBuilder.Entity("UserAccessRequest.Model.Database.RequestForms", b =>
                {
                    b.Navigation("RequestFormsResult");
                });
#pragma warning restore 612, 618
        }
    }
}
